set nocompatible    " Get rid of Vi compatibility mode.

syntax enable       " Highlight syntax

set encoding=utf-8  " Unicode
set wrap            " Handle long lines

set hlsearch        " Highlight search
set ignorecase      " Ignore case when searching

set list            " Show hidden characters
set listchars=tab:›\ ,trail:•,extends:#,nbsp:.

set tabstop=4       " Tab spacing
"set shiftwidth=4    " indent/outdent by 4 columns
set shiftround      " always indent/outdent to the nearest tabstop
set expandtab       " use spaces instead of tabs
set smarttab        " Use tabs at the start of a line(spaces elsewhere)

" .rasi syntax
au BufNewFile,BufRead /*.rasi setf css

set paste
