#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap us &
nitrogen --restore &
/home/snekyy/.config/polybar/launch.sh &
/home/snekyy/.config/picom/launch.sh &
xsetroot -cursor_name left_ptr &

# Virtual desktops count
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
