#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/home/snekyy/.config/polybar/launch.sh &
/home/snekyy/.config/picom/launch.sh &

# Virtual desktops count
bspc monitor -d I II III IV V VI

bspc config border_width         4 
bspc config window_gap			4 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
